# Server
server.port=${PORT:8080}

# Application
spring.application.name=graphoria-backend

# Database (Render will inject these)
spring.datasource.url = ${SPRING_DATASOURCE_URL}
spring.datasource.username = ${SPRING_DATASOURCE_USERNAME}
spring.datasource.password = ${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name = org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Optional logging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
